pages/urls.py
from django.conf.urls import url
from . import views
from wkhtmltopdf.views import PDFTemplateView
urlpatterns = [
    url(r'dashboard/', views.index, name='index'),
    url(r'chart-creation/', views.chartcreation, name='chart-creation'),
    url(r'data-selection/', views.dataselection, name='data-selection'),
    url(r'create-chartset-redirect/', views.createchartset, name='create-chartset-redirect'),
    url(r'confirm-chart-redirect/', views.confirmchartredirect, name='confirm-chart-redirect'), 
    url(r'delete-chart-redirect/', views.deletechartredirect, name='delete-chart-redirect'),
    url(r'save-chartset-redirect/', views.savechartsetredirect, name='save-chartset-redirect'),
    url(r'change-chartset-redirect/', views.changechartset, name='change-chartset-redirect'),
    url(r'change-selected-chart-redirect/', views.changeselectedchartredirect, name='change-selected-chart-redirect'), 
    url(r'select-dataset-redirect/', views.selectdatasetredirect, name='select-dataset-redirect'),
    url(r'report/', views.reportview, name='report'),
    url(r'db-updater/', views.updatedb, name='db-updater'),
    url(r'db-updater-all-redirect/', views.updatedballredirect, name='db-updater-all-redirect'),
    url(r'db-updater-week-redirect/', views.updatedbweekredirect, name='db-updater-week-redirect'),
    url(r'^$', views.blankredirect, name='blank-redirect')
]

rec_data_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

pages/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import ModelChoiceField
from django.forms.widgets import *
from pages.models import *
import datetime

'''Used to select the variables that define the dataset queries'''
class DatasetForm(forms.Form):
    label = forms.CharField(max_length=40)
    facility = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple(), initial=('all', 'All'), 
                                         choices=(('all', 'All'), ('rec', 'Rec Center'), ('clawson', 'Clawson'), ('nq', 'North Quad')))
    area = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple(), initial=('all', 'All'), 
                                         choices=(('all','All'), ('fc','Fitness Center'), ('gf', 'Group Fitness')))
    start_date = forms.DateTimeField(label="Start Date", initial=datetime.datetime.now().strftime("%Y-%m-%d"))
    end_date = forms.DateTimeField(label='End Date', initial=datetime.datetime.now().strftime("%Y-%m-%d"))
    units = forms.ChoiceField(choices = (('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('all', 'One Group')), label='Increment Units')
    gender = forms.ChoiceField(choices=(('all', 'All'), ('m', 'Male'), ('f', 'Female')), label='Gender')
    color = forms.ChoiceField(choices=(('rgb(0, 0, 0, .6)', 'Black'), ('rgb(255, 0, 0, .6)', 'Red'), ('rgb(255, 127, 0, .6)', 'Orange'), ('rgb(255, 255, 0, .6)', 'Yellow'), 
                                        ('rgb(127, 255, 0, .6)', 'Light Green'), ('rgb(0, 255, 0, .6)', 'Green'), ('rgb(0, 255, 127, .6)', 'Blue Green'),
                                        ('rgb(0, 255, 255, .6)', 'Cyan'), ('rgb(0, 0, 255, .6)', 'Blue'), ('rgb(127, 0, 255, .6)', 'Violet'), 
                                        ('rgb(255, 0, 255, .6)', 'Magenta')))
    time = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('6:30', '6:30'), ('7:30', '7:30'), ('8:30', '8:30'), ('9:30', '9:30'),
                                            ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'),
                                            ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30'), ('19:30', '19:30'),
                                            ('20:30', '20:30'), ('21:30', '21:30'), ('22:30', '22:30')))
    year = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'),
                                            ('2011', '2011'), ('2010', '2010'),('2009', '2009'), ('2008', '2008'),('2007', '2007'), ('2006', '2006')))
    month = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'),
                                            ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'),('11', 'November'), ('12', 'December')))
    week = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'),
                                              ('7', 'Week 7'), ('8', 'Week 8'), ('9', 'Week 9'),('10', 'Week 10'), ('11', 'Week 11'),('12', 'Week 12'),
                                              ('13', 'Week 13'), ('14', 'Week 14'), ('15', 'Week 15'), ('16', 'Week 16'), ('17', 'Week 17'),
                                              ('18', 'Week 18'), ('19', 'Week 19'), ('20', 'Week 20'), ('21', 'Week 21'), ('22', 'Week 22'),
                                              ('23', 'Week 23'), ('24', 'Week 24'), ('25', 'Week 25'), ('26', 'Week 26'), ('27', 'Week 27'),
                                              ('28', 'Week 28'), ('29', 'Week 29'), ('30', 'Week 30'), ('31', 'Week 31'), ('32', 'Week 32'),
                                              ('33', 'Week 33'), ('34', 'Week 34'), ('35', 'Week 35'), ('36', 'Week 36'), ('37', 'Week 37'),
                                              ('38', 'Week 38'), ('39', 'Week 39'), ('40', 'Week 40'), ('41', 'Week 41'), ('42', 'Week 42'),
                                              ('43', 'Week 43'), ('44', 'Week 44'), ('45', 'Week 45'), ('46', 'Week 46'), ('47', 'Week 47'),
                                              ('48', 'Week 48'), ('49', 'Week 49'), ('50', 'Week 50'), ('51', 'Week 51'), ('52', 'Week 52'),
                                              ('53', 'Week 53')))
    day_of_month = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6'),
                                                     ('7', 'Day 7'), ('8', 'Day 8'), ('9', 'Day 9'), ('10', 'Day 10'), ('11', 'Day 11'), ('12', 'Day 12'),
                                                     ('13', 'Day 13'), ('14', 'Day 14'), ('15', 'Day 15'), ('16', 'Day 16'), ('17', 'Day 17'),
                                                     ('18', 'Day 18'), ('19', 'Day 19'), ('20', 'Day 20'), ('21', 'Day 21'), ('22', 'Day 22'),
                                                     ('23', 'Day 23'), ('24', 'Day 24'), ('25', 'Day 25'), ('26', 'Day 26'), ('27', 'Day 27'),
                                                     ('28', 'Day 28'), ('29', 'Day 29'), ('30', 'Day 30'), ('31', 'Day 31')))
    day_of_week = forms.MultipleChoiceField(initial=('all', 'All'), choices=(('all', 'All'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'),
                                                     ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')))

'''Used to define a chart's type on the chart creation page'''
class ChartForm(forms.Form):
    type = forms.ChoiceField(initial=('line', 'Line Chart'), required=True, widget=forms.RadioSelect(), choices=(('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'),
                                                  ('scatter', 'Scatter Plot')))

'''Used to name a template on the home page'''
class SaveTemplateForm(forms.Form):
    name = forms.CharField()

'''Helper method that displays the names of saved templates to select from'''
class SelectTemplateChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return str(obj.name)

'''Used to select a different template on the home page'''
class SelectTemplateForm(forms.Form):
    name = SelectTemplateChoiceField(queryset = ChartSet.objects.filter(saved=1), widget=forms.RadioSelect(), empty_label=None)

'''Used to select a chart on the home page'''
class SelectChartForm(forms.Form):
    selected_chart_id = forms.CharField()

'''Used to select a graph on the chart creation page'''
class SelectGraphForm(forms.Form):
    selected_graph_id = forms.CharField()

'''Used to update one week of the database on the update page'''
class UpdateWeekDBForm(forms.Form):
    date = forms.DateTimeField(label='Date', initial=datetime.datetime.now().strftime("%Y-%m-%d"))
    type_week = forms.ChoiceField(initial=('all', 'All'), required=True, widget=forms.RadioSelect(), choices=(('all', 'All'), ('Rec Patron Counts', 'Rec Center'), ('North Quad', 'North Quad'),
                                                  ('Clawson', 'Clawson')))

'''Used to update alll weeks of the database on the update page'''
class UpdateAllDBForm(forms.Form):
    type_all = forms.ChoiceField(initial=('all', 'All'), required=True, widget=forms.RadioSelect(), choices=(('all', 'All'), ('Rec Patron Counts', 'Rec Center'), ('North Quad', 'North Quad'),
                                                  ('Clawson', 'Clawson')))

templates/pages/data-selection.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Data Selection</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/data-selection.css' %}">
        <link rel="icon" href="{% static 'img/logo.png' %}">
        <link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
            $.noConflict();
            jQuery(document).ready(function ($) {
                $("#id_start_date").datepicker({dateFormat: "yy-mm-dd"});
            });
            jQuery(document).ready(function ($) {
                $("#id_end_date").datepicker({dateFormat: "yy-mm-dd"});
            });
        </script>

        
    </head>
    <body>
        <div class="container entire-body">
            <div class="row justify-content-start">
                <div class="col-0">
                    <button type="button" class="btn btn-outline-primary" id="chart-back-button"><a href="{% url 'chart-creation' %}">Back</a></button>
                </div>
            </div>
            
            <!--Facilities-->
            <form action="/chart-creation/" method="POST" class="form-group">
                {% csrf_token %}
                {% for field in dataset_form %}
                    {% if field.label == 'Label' or field.label == 'Facility' or field.label == 'Area' %}
                        <div class='row justify-content-center form-row'>
                            <div class='col-12'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                        </div>
                    {% elif field.label == 'Start Date'%}
                        <div class="row justify-content-center form-row">
                            <div class='col-4'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                    {% elif field.label == 'End Date'%}
                        <div class='col-4'>
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% elif field.label == 'Increment Units'%}
                            <div class='col-4'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                        </div>
                    {% elif field.label == 'Gender'%}
                        <div class="row justify-content-center align-items-center form-row">
                            <div class='col-4'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                    {% elif field.label == 'Color'%}
                        <div class='col-4'>
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% elif field.label == 'Time'%}
                            <div class='col-4'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                        </div>
                    {% elif field.label == 'Year'%}
                        <div class="row justify-content-center align-items-center form-row">
                            <div class='col-2'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                    {% elif field.label == 'Month'%}
                        <div class='col-2'>
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% elif field.label == 'Week'%}
                        <div class='col-2'>
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% elif field.label == 'Day of month'%}
                        <div class='col-2'>
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% elif field.label == 'Day of week'%}
                            <div class='col-2'>
                                {{field.label}}
                                {{ field }} 
                            </div>
                        </div>
                    {% else %}
                        <div class="col-2">
                            {{field.label}}
                            {{ field }} 
                        </div>
                    {% endif %}         
                {% endfor %}
                <div class="row">
                    <div class="col-12">
                        <p class="tip">* Hold 'Ctrl' and click to select multiple options, hold 'Shift' and click to select consecutive options</p>
                    </div>
                </div>
                
            
                <div class="row justify-content-center">
                    <div class="col-0">
                        <input type="submit" value="Select" class="btn btn-outline-primary facility-button" id="data-select-confirm">
                    </div>
                </div>
            </form>
        </div>
    </body> 
    <script>
        if('{{use_json}}'=='True') {
            function splitElements(string) {
                string = string.replace('[', '');
                string = string.replace(']', '');
                string = string.replace(/'/g, "");
                string = string.replace(/ /g, "");
                string = string.split(",");
                return string;
            }

            var graph_json = {{graph_json|safe}};
            document.getElementById('id_label').value = graph_json.label;
            for(facility in splitElements(graph_json.facility)) {
                for(var f = 0; f<4; f++) { //4 is the number of areas in DatasetForm
                    document.getElementById('id_facility_'+f).checked = false;  
                    if(splitElements(graph_json.facility)[facility]==document.getElementById('id_facility_'+f).value) {
                        document.getElementById('id_facility_'+f).checked = true;
                    }
                }
            }   
            for(area in splitElements(graph_json.area)) {
                for(var a = 0; a<3; a++) { //6 is the number of areas in DatasetForm
                    document.getElementById('id_area_'+a).checked = false;
                    if(splitElements(graph_json.area)[area]==document.getElementById('id_area_'+a).value) {
                        document.getElementById('id_area_'+a).checked = true;
                    }
                }
            }   
            document.getElementById('id_start_date').value = graph_json.start_date;
            document.getElementById('id_end_date').value = graph_json.end_date;
            document.getElementById('id_units').value = graph_json.unit;
            document.getElementById('id_gender').value = graph_json.gender;
            for(year in splitElements(graph_json.year)) {
                for(var y = 0; y<14; y++) { //14 is the number of years in DatasetForm
                    document.getElementById('id_year')[y].selected = false;
                    if(splitElements(graph_json.year)[year]==document.getElementById('id_year')[y].value) {
                        document.getElementById('id_year')[y].selected = true;
                    }
                }
            }   
            for(month in splitElements(graph_json.month)) {
                for(var m = 0; m<13; m++) { //13 is the number of months in DatasetForm
                    document.getElementById('id_month')[m].selected = false;
                    if(splitElements(graph_json.month)[month]==document.getElementById('id_month')[m].value) {
                        document.getElementById('id_month')[m].selected = true;
                    }
                }
            }   
            for(week in splitElements(graph_json.week)) {
                for(var w = 0; w<54; w++) { //54 is the number of weeks in DatasetForm
                    document.getElementById('id_week')[w].selected = false;
                    if(splitElements(graph_json.week)[week]==document.getElementById('id_week')[w].value) {
                        document.getElementById('id_week')[w].selected = true;
                    }
                }
            } 
            for(day_of_month in splitElements(graph_json.day_of_month)) {
                for(var dom = 0; dom<32; dom++) { //32 is the number of days in DatasetForm
                    document.getElementById('id_day_of_month')[dom].selected = false;
                    if(splitElements(graph_json.day_of_month)[day_of_month]==document.getElementById('id_day_of_month')[dom].value) {
                        document.getElementById('id_day_of_month')[dom].selected = true;
                    }
                }
            }   
            for(day_of_week in splitElements(graph_json.day_of_week)) {
                for(var dow = 0; dow<8; dow++) { //8 is the number of weeks in DatasetForm
                    document.getElementById('id_day_of_week')[dow].selected = false;
                    if(splitElements(graph_json.day_of_week)[day_of_week]==document.getElementById('id_day_of_week')[dow].value) {
                        document.getElementById('id_day_of_week')[dow].selected = true;
                    }
                }
            }   
            for(time in splitElements(graph_json.time)) {
                for(var t = 0; t<8; t++) { //8 is the number of weeks in DatasetForm
                    document.getElementById('id_time')[t].selected =false;
                    if(splitElements(graph_json.time)[time]==document.getElementById('id_time')[t].value) {
                        document.getElementById('id_time')[t].selected = true;
                    }
                }
            }           
            document.getElementById('id_color').value = graph_json.color;
        }
        else{
            var graph_json = {{graph_json|safe}};
            document.getElementById('id_units').value = graph_json.unit;
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/pages/edit-dataset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Data Selection</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/data-selection.css' %}">
        <link rel="icon" href="{% static 'img/logo.png' %}">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
            $.noConflict();
            jQuery(document).ready(function ($) {
                $("#id_start_date").datepicker({dateFormat: "yy-mm-dd"});
            });
            jQuery(document).ready(function ($) {
                $("#id_end_date").datepicker({dateFormat: "yy-mm-dd"});
            });
        </script>

        
    </head>
    <body>
        <div class="container entire-body">
            <div class="row justify-content-start">
                <div class="col-0">
                    <button type="button" class="btn btn-outline-primary" id="chart-back-button"><a href="{% url 'edit-chart' %}">Back</a></button>
                </div>
            </div>
            
            <!--Facilities-->
            <form action="/edit-chart/" method="POST" class="form-group">
                {% csrf_token %}
                {{ dataset_form }} 
            
                <div class="row justify-content-center">
                    <div class="col-0">
                        <input type="submit" value="Select" class="btn btn-outline-primary facility-button" id="data-select-confirm">
                    </div>
                </div>
            </form>
        </div>
    </body> 
    <script>
        if('{{use_json}}'=='True') {
            function splitElements(string) {
                string = string.replace('[', '');
                string = string.replace(']', '');
                string = string.replace(/'/g, "");
                string = string.replace(/ /g, "");
                string = string.split(",");
                return string;
            }

            var graph_json = {{graph_json|safe}};
            document.getElementById('id_label').value = graph_json.label;
            for(facility in splitElements(graph_json.facility)) {
                for(var f = 0; f<4; f++) { //4 is the number of areas in DatasetForm
                    if(splitElements(graph_json.facility)[facility]==document.getElementById('id_facility_'+f).value) {
                        document.getElementById('id_facility_'+f).checked = true;
                    }
                }
            }   
            for(area in splitElements(graph_json.area)) {
                for(var a = 0; a<6; a++) { //6 is the number of areas in DatasetForm
                    if(splitElements(graph_json.area)[area]==document.getElementById('id_area_'+a).value) {
                        document.getElementById('id_area_'+a).checked = true;
                    }
                }
            }   
            document.getElementById('id_start_date').value = graph_json.start_date;
            document.getElementById('id_end_date').value = graph_json.end_date;
            document.getElementById('id_units').value = graph_json.unit;
            document.getElementById('id_gender').value = graph_json.gender;
            for(year in splitElements(graph_json.year)) {
                for(var y = 0; y<14; y++) { //14 is the number of years in DatasetForm
                    if(splitElements(graph_json.year)[year]==document.getElementById('id_year')[y].value) {
                        document.getElementById('id_year')[y].selected = true;
                    }
                }
            }   
            for(month in splitElements(graph_json.month)) {
                for(var m = 0; m<13; m++) { //13 is the number of months in DatasetForm
                    if(splitElements(graph_json.month)[month]==document.getElementById('id_month')[m].value) {
                        document.getElementById('id_month')[m].selected = true;
                    }
                }
            }   
            for(week in splitElements(graph_json.week)) {
                for(var w = 0; w<54; w++) { //54 is the number of weeks in DatasetForm
                    if(splitElements(graph_json.week)[week]==document.getElementById('id_week')[w].value) {
                        document.getElementById('id_week')[w].selected = true;
                    }
                }
            } 
            for(day_of_month in splitElements(graph_json.day_of_month)) {
                for(var dom = 0; dom<32; dom++) { //32 is the number of days in DatasetForm
                    if(splitElements(graph_json.day_of_month)[day_of_month]==document.getElementById('id_day_of_month')[dom].value) {
                        document.getElementById('id_day_of_month')[dom].selected = true;
                    }
                }
            }   
            for(day_of_week in splitElements(graph_json.day_of_week)) {
                for(var dow = 0; dow<8; dow++) { //8 is the number of weeks in DatasetForm
                    if(splitElements(graph_json.day_of_week)[day_of_week]==document.getElementById('id_day_of_week')[dow].value) {
                        document.getElementById('id_day_of_week')[dow].selected = true;
                    }
                }
            }   
            for(time in splitElements(graph_json.time)) {
                for(var t = 0; t<8; t++) { //8 is the number of weeks in DatasetForm
                    if(splitElements(graph_json.time)[time]==document.getElementById('id_time')[t].value) {
                        document.getElementById('id_time')[t].selected = true;
                    }
                }
            }           
            document.getElementById('id_color').value = graph_json.color;
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/pages/test-chart-template.html
{% load static %}

{% block chart %}
    <canvas id="template-chart" width="500" height="300"></canvas>

    <script src="{% static 'js/chartjs/dist/Chart.js' %}" type="text/javascript"></script>
    <script>
        var ctx = document.getElementById("template-chart");
        var testChart = new Chart(ctx, {});
        var titles = ['1' , '2', '3', '4'] ;
        var radio = document.getElementById('id_type');

        radio.onchange = function() {
            if(document.getElementById('id_type_0').checked) {
                var chart_type = 'line'
            }
            else if(document.getElementById('id_type_1').checked) {
                var chart_type = 'bar'
            }
            else if(document.getElementById('id_type_2').checked) {
                var chart_type = 'pie'
            }
            else if(document.getElementById('id_type_3').checked) {
                var chart_type = 'scatter'
            }
            var title_index = 0;
            testChart.destroy();
            testChart = new Chart(ctx, {
                type: chart_type,
                data: {
                    labels: titles,
                    datasets: [
                        {% for x in values %}
                        {
                            label: titles[title_index++],
                            data: {{ x|safe }},
                        backgroundColor: [
                            'rgba(0, 0, 255, 0.2)'
                            ],
                        borderColor: [
                            'rgba(0,99,132,1)'
                        ],
                            borderWidth: 1
                        },
                        {% endfor %}
                    ]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        };

        var title_index = 0;
        testChart = new Chart(ctx, {
            type: 'line',
                data: {
                    labels: titles,
                    datasets: [
                    {% for x in values %}
                    {
                        label: titles[title_index++],
                        data: {{ x|safe }},
                    backgroundColor: [
                        'rgba(0, 0, 255, 0.2)'
                        ],
                    borderColor: [
                        'rgba(0,99,132,1)'
                    ],
                        borderWidth: 1
                    },
                    {% endfor %}
                    ]
                },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}